// Generated by https://quicktype.io
import Image from 'next/image'
import { actor } from "./type/types"

interface actortypes {
  mindex: number;
  mdata: actor;
}

const NinjaCard = (props: actortypes) => {

  const item = props.mdata;
  const index = props.mindex;

  return (

    <div key={index} className="grid grid-cols-2 shadow-[0px_0px_15px_0px] rounded-lg bg-white">
      <div className="bg-yellow-500 rounded-lg overflow-hidden m-2 ">

        <Image
          src={item.image}
          priority={true}
          alt="image description"
          width={150}
          height={150}
          //fill
          className='mx-auto'
        />
      </div>

      <div className="grid grid-row-3 mt-1 mr-2 mb-2 md:mb-2 lg:mb-2">

        <div className="text-lg font-Barriecito">{item.name}</div>
        <div className="h-32">{item.description}</div>
        <div className="text-left">
          <button className="btn-read">
            Read more
          </button>

        </div>

      </div>

    </div>

  )

}

export default NinjaCard;